#!/bin/sh
mv GameData/Squad/Parts/Aero/advancedCanard/model000.mbm GameData/Squad/Parts/Aero/advancedCanard/model000.mbmbak
mv GameData/Squad/Parts/Aero/advancedCanard/model001.mbm GameData/Squad/Parts/Aero/advancedCanard/model001.mbmbak
mv GameData/Squad/Parts/Aero/aerodynamicNoseCone/model.mu GameData/Squad/Parts/Aero/aerodynamicNoseCone/model.mubak
mv GameData/Squad/Parts/Aero/aerodynamicNoseCone/model000.mbm GameData/Squad/Parts/Aero/aerodynamicNoseCone/model000.mbmbak
mv GameData/Squad/Parts/Aero/noseConeAdapter/model.mu GameData/Squad/Parts/Aero/noseConeAdapter/model.mubak
mv GameData/Squad/Parts/Aero/noseConeAdapter/model000.mbm GameData/Squad/Parts/Aero/noseConeAdapter/model000.mbmbak
mv GameData/Squad/Parts/Aero/noseConeAdapter/model001.mbm GameData/Squad/Parts/Aero/noseConeAdapter/model001.mbmbak
mv GameData/Squad/Parts/Aero/protectiveRocketNoseMk7/model.mu GameData/Squad/Parts/Aero/protectiveRocketNoseMk7/model.mubak
mv GameData/Squad/Parts/Aero/protectiveRocketNoseMk7/model000.mbm GameData/Squad/Parts/Aero/protectiveRocketNoseMk7/model000.mbmbak
mv GameData/Squad/Parts/Aero/standardCanard/model.mu GameData/Squad/Parts/Aero/standardCanard/model.mubak
mv GameData/Squad/Parts/Aero/standardCanard/model000.mbm GameData/Squad/Parts/Aero/standardCanard/model000.mbmbak
mv GameData/Squad/Parts/Aero/standardCanard/model001.mbm GameData/Squad/Parts/Aero/standardCanard/model001.mbmbak
mv GameData/Squad/Parts/Aero/standardNoseCone/model.mu GameData/Squad/Parts/Aero/standardNoseCone/model.mubak
mv GameData/Squad/Parts/Aero/standardNoseCone/model000.mbm GameData/Squad/Parts/Aero/standardNoseCone/model000.mbmbak
mv GameData/Squad/Parts/Aero/standardNoseCone/model001.mbm GameData/Squad/Parts/Aero/standardNoseCone/model001.mbmbak
mv GameData/Squad/Parts/Aero/sweptWing/model.mu GameData/Squad/Parts/Aero/sweptWing/model.mubak
mv GameData/Squad/Parts/Aero/sweptWing/model000.mbm GameData/Squad/Parts/Aero/sweptWing/model000.mbmbak
mv GameData/Squad/Parts/Aero/sweptWing/model001.mbm GameData/Squad/Parts/Aero/sweptWing/model001.mbmbak
mv GameData/Squad/Parts/Aero/tailConnector/model.mu GameData/Squad/Parts/Aero/tailConnector/model.mubak
mv GameData/Squad/Parts/Aero/tailConnector/model000.mbm GameData/Squad/Parts/Aero/tailConnector/model000.mbmbak
mv GameData/Squad/Parts/Aero/tailfin/model.mu GameData/Squad/Parts/Aero/tailfin/model.mubak
mv GameData/Squad/Parts/Aero/tailfin/model000.mbm GameData/Squad/Parts/Aero/tailfin/model000.mbmbak
mv GameData/Squad/Parts/Aero/tailfin/model001.mbm GameData/Squad/Parts/Aero/tailfin/model001.mbmbak
mv GameData/Squad/Parts/Aero/wingletAV-R8/model.mu GameData/Squad/Parts/Aero/wingletAV-R8/model.mubak
mv GameData/Squad/Parts/Aero/wingletAV-R8/model000.tga GameData/Squad/Parts/Aero/wingletAV-R8/model000.tgabak
mv GameData/Squad/Parts/Aero/wingletAV-R8/model001.tga GameData/Squad/Parts/Aero/wingletAV-R8/model001.tgabak
mv GameData/Squad/Parts/Aero/wingletAV-R8/model002_NRM.tga GameData/Squad/Parts/Aero/wingletAV-R8/model002_NRM.tgabak
mv GameData/Squad/Parts/Aero/wingletDeltaDeluxe/model000.mbm GameData/Squad/Parts/Aero/wingletDeltaDeluxe/model000.mbmbak
mv GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin.mbm GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin.mbmbak
mv GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin_LUM.mbm GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin_LUM.mbmbak
mv GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin_n.mbm GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin_n.mbmbak
mv GameData/Squad/Parts/Command/hitchhikerStorageContainer/model.mu GameData/Squad/Parts/Command/hitchhikerStorageContainer/model.mubak
mv GameData/Squad/Parts/Command/Mk1-2Pod/ladder.mbm GameData/Squad/Parts/Command/Mk1-2Pod/ladder.mbmbak
mv GameData/Squad/Parts/Command/Mk1-2Pod/mk\ 1-2\ external\ shell\ Variant-Hatch\ NRM.mbm GameData/Squad/Parts/Command/Mk1-2Pod/mk\ 1-2\ external\ shell\ Variant-Hatch\ NRM.mbmbak
mv GameData/Squad/Parts/Command/Mk1-2Pod/mk\ 1-2\ external\ shell\ Variant-Hatch.mbm GameData/Squad/Parts/Command/Mk1-2Pod/mk\ 1-2\ external\ shell\ Variant-Hatch.mbmbak
mv GameData/Squad/Parts/Command/Mk1-2Pod/model.mu GameData/Squad/Parts/Command/Mk1-2Pod/model.mubak
mv GameData/Squad/Parts/Command/mk1Cockpit/mk1Cockpit.mbm GameData/Squad/Parts/Command/mk1Cockpit/mk1Cockpit.mbmbak
mv GameData/Squad/Parts/Command/mk1Cockpit/mk1cockpit_LUM.mbm GameData/Squad/Parts/Command/mk1Cockpit/mk1cockpit_LUM.mbmbak
mv GameData/Squad/Parts/Command/mk1Cockpit/mk1cockpit_NRM.mbm GameData/Squad/Parts/Command/mk1Cockpit/mk1cockpit_NRM.mbmbak
mv GameData/Squad/Parts/Command/mk1Cockpit/model.mu GameData/Squad/Parts/Command/mk1Cockpit/model.mubak
mv GameData/Squad/Parts/Command/mk1pod/hatch.mbm GameData/Squad/Parts/Command/mk1pod/hatch.mbmbak
mv GameData/Squad/Parts/Command/mk1pod/model.mu GameData/Squad/Parts/Command/mk1pod/model.mubak
mv GameData/Squad/Parts/Command/mk1pod/outer\ shell\ NRM.mbm GameData/Squad/Parts/Command/mk1pod/outer\ shell\ NRM.mbmbak
mv GameData/Squad/Parts/Command/mk1pod/outer\ shell.mbm GameData/Squad/Parts/Command/mk1pod/outer\ shell.mbmbak
mv GameData/Squad/Parts/Command/mk2LanderCan/ladder.mbm GameData/Squad/Parts/Command/mk2LanderCan/ladder.mbmbak
mv GameData/Squad/Parts/Command/mk2LanderCan/model.mu GameData/Squad/Parts/Command/mk2LanderCan/model.mubak
mv GameData/Squad/Parts/Command/mk2LanderCan/outershell.mbm GameData/Squad/Parts/Command/mk2LanderCan/outershell.mbmbak
mv GameData/Squad/Parts/Command/mk2LanderCan/outershell_n.mbm GameData/Squad/Parts/Command/mk2LanderCan/outershell_n.mbmbak
mv GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/model.mu GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/model.mubak
mv GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/model000.mbm GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/model000.mbmbak
mv GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/model001.mbm GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/model001.mbmbak
mv GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/SHieldbox_CLR.mbm GameData/Squad/Parts/Electrical/1x6ShroudSolarPanels/SHieldbox_CLR.mbmbak
mv GameData/Squad/Parts/Electrical/1x6SolarPanels/model.mu GameData/Squad/Parts/Electrical/1x6SolarPanels/model.mubak
mv GameData/Squad/Parts/Electrical/1x6SolarPanels/model000.mbm GameData/Squad/Parts/Electrical/1x6SolarPanels/model000.mbmbak
mv GameData/Squad/Parts/Electrical/1x6SolarPanels/model001.mbm GameData/Squad/Parts/Electrical/1x6SolarPanels/model001.mbmbak
mv GameData/Squad/Parts/Electrical/gigantorXlSolarArray/model.mu GameData/Squad/Parts/Electrical/gigantorXlSolarArray/model.mubak
mv GameData/Squad/Parts/Electrical/gigantorXlSolarArray/model000.mbm GameData/Squad/Parts/Electrical/gigantorXlSolarArray/model000.mbmbak
mv GameData/Squad/Parts/Electrical/gigantorXlSolarArray/model001.mbm GameData/Squad/Parts/Electrical/gigantorXlSolarArray/model001.mbmbak
mv GameData/Squad/Parts/Electrical/radialFlatSolarPanel/model.mu GameData/Squad/Parts/Electrical/radialFlatSolarPanel/model.mubak
mv GameData/Squad/Parts/Electrical/radialFlatSolarPanel/model000.mbm GameData/Squad/Parts/Electrical/radialFlatSolarPanel/model000.mbmbak
mv GameData/Squad/Parts/Electrical/radialFlatSolarPanel/model001.mbm GameData/Squad/Parts/Electrical/radialFlatSolarPanel/model001.mbmbak
mv GameData/Squad/Parts/Electrical/RTG/model.mu GameData/Squad/Parts/Electrical/RTG/model.mubak
mv GameData/Squad/Parts/Electrical/RTG/model000.mbm GameData/Squad/Parts/Electrical/RTG/model000.mbmbak
mv GameData/Squad/Parts/Electrical/z-100Battery/model.mu GameData/Squad/Parts/Electrical/z-100Battery/model.mubak
mv GameData/Squad/Parts/Electrical/z-100Battery/model000.mbm GameData/Squad/Parts/Electrical/z-100Battery/model000.mbmbak
mv GameData/Squad/Parts/Electrical/z-1kBattery/model.mu GameData/Squad/Parts/Electrical/z-1kBattery/model.mubak
mv GameData/Squad/Parts/Electrical/z-1kBattery/model000.mbm GameData/Squad/Parts/Electrical/z-1kBattery/model000.mbmbak
mv GameData/Squad/Parts/Electrical/z-1kBattery/model001.mbm GameData/Squad/Parts/Electrical/z-1kBattery/model001.mbmbak
mv GameData/Squad/Parts/Electrical/z-200Battery/model.mu GameData/Squad/Parts/Electrical/z-200Battery/model.mubak
mv GameData/Squad/Parts/Electrical/z-200Battery/model000.mbm GameData/Squad/Parts/Electrical/z-200Battery/model000.mbmbak
mv GameData/Squad/Parts/Electrical/z-200Battery/model001.mbm GameData/Squad/Parts/Electrical/z-200Battery/model001.mbmbak
mv GameData/Squad/Parts/Electrical/z-400Battery/model.mu GameData/Squad/Parts/Electrical/z-400Battery/model.mubak
mv GameData/Squad/Parts/Electrical/z-400Battery/model000.mbm GameData/Squad/Parts/Electrical/z-400Battery/model000.mbmbak
mv GameData/Squad/Parts/Electrical/z-4kBattery/model.mu GameData/Squad/Parts/Electrical/z-4kBattery/model.mubak
mv GameData/Squad/Parts/Electrical/z-4kBattery/model000.mbm GameData/Squad/Parts/Electrical/z-4kBattery/model000.mbmbak
mv GameData/Squad/Parts/Electrical/z-4kBattery/model001.mbm GameData/Squad/Parts/Electrical/z-4kBattery/model001.mbmbak
mv GameData/Squad/Parts/Engine/jetEngineBasic/model.mu GameData/Squad/Parts/Engine/jetEngineBasic/model.mubak
mv GameData/Squad/Parts/Engine/jetEngineBasic/model000.mbm GameData/Squad/Parts/Engine/jetEngineBasic/model000.mbmbak
mv GameData/Squad/Parts/Engine/jetEngineBasic/model001.mbm GameData/Squad/Parts/Engine/jetEngineBasic/model001.mbmbak
mv GameData/Squad/Parts/Engine/jetEngineBasic/model002.mbm GameData/Squad/Parts/Engine/jetEngineBasic/model002.mbmbak
mv GameData/Squad/Parts/Engine/jetEngineTurbo/model.mu GameData/Squad/Parts/Engine/jetEngineTurbo/model.mubak
mv GameData/Squad/Parts/Engine/jetEngineTurbo/model000.mbm GameData/Squad/Parts/Engine/jetEngineTurbo/model000.mbmbak
mv GameData/Squad/Parts/Engine/jetEngineTurbo/model001.mbm GameData/Squad/Parts/Engine/jetEngineTurbo/model001.mbmbak
mv GameData/Squad/Parts/Engine/jetEngineTurbo/model002.mbm GameData/Squad/Parts/Engine/jetEngineTurbo/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineAerospike/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEngineAerospike/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineAerospike/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEngineAerospike/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineAerospike/model.mu GameData/Squad/Parts/Engine/liquidEngineAerospike/model.mubak
mv GameData/Squad/Parts/Engine/liquidEngineAerospike/model000.mbm GameData/Squad/Parts/Engine/liquidEngineAerospike/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineAerospike/model001.mbm GameData/Squad/Parts/Engine/liquidEngineAerospike/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineAerospike/model002.mbm GameData/Squad/Parts/Engine/liquidEngineAerospike/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineAerospike/model003.mbm GameData/Squad/Parts/Engine/liquidEngineAerospike/model003.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-909/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEngineLV-909/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-909/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEngineLV-909/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-909/model.mu GameData/Squad/Parts/Engine/liquidEngineLV-909/model.mubak
mv GameData/Squad/Parts/Engine/liquidEngineLV-909/model000.mbm GameData/Squad/Parts/Engine/liquidEngineLV-909/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-909/model001.mbm GameData/Squad/Parts/Engine/liquidEngineLV-909/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-909/model002.mbm GameData/Squad/Parts/Engine/liquidEngineLV-909/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-N/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEngineLV-N/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-N/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEngineLV-N/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-N/model.mu GameData/Squad/Parts/Engine/liquidEngineLV-N/model.mubak
mv GameData/Squad/Parts/Engine/liquidEngineLV-N/model000.mbm GameData/Squad/Parts/Engine/liquidEngineLV-N/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-N/model001.mbm GameData/Squad/Parts/Engine/liquidEngineLV-N/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-N/model002.mbm GameData/Squad/Parts/Engine/liquidEngineLV-N/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T30/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T30/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T30/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T30/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T30/model.mu GameData/Squad/Parts/Engine/liquidEngineLV-T30/model.mubak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T30/model000.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T30/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T30/model001.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T30/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T30/model002.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T30/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T45/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T45/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T45/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T45/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T45/model.mu GameData/Squad/Parts/Engine/liquidEngineLV-T45/model.mubak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T45/model000.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T45/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T45/model001.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T45/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineLV-T45/model002.mbm GameData/Squad/Parts/Engine/liquidEngineLV-T45/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMainsail/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEngineMainsail/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMainsail/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEngineMainsail/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMainsail/model.mu GameData/Squad/Parts/Engine/liquidEngineMainsail/model.mubak
mv GameData/Squad/Parts/Engine/liquidEngineMainsail/model000.mbm GameData/Squad/Parts/Engine/liquidEngineMainsail/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMainsail/model001.mbm GameData/Squad/Parts/Engine/liquidEngineMainsail/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMainsail/model002.mbm GameData/Squad/Parts/Engine/liquidEngineMainsail/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMk55/model.mu GameData/Squad/Parts/Engine/liquidEngineMk55/model.mubak
mv GameData/Squad/Parts/Engine/liquidEngineMk55/model000.mbm GameData/Squad/Parts/Engine/liquidEngineMk55/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMk55/model001.mbm GameData/Squad/Parts/Engine/liquidEngineMk55/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineMk55/model002.mbm GameData/Squad/Parts/Engine/liquidEngineMk55/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEnginePoodle/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEnginePoodle/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEnginePoodle/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEnginePoodle/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEnginePoodle/model.mu GameData/Squad/Parts/Engine/liquidEnginePoodle/model.mubak
mv GameData/Squad/Parts/Engine/liquidEnginePoodle/model000.mbm GameData/Squad/Parts/Engine/liquidEnginePoodle/model000.mbmbak
mv GameData/Squad/Parts/Engine/liquidEnginePoodle/model001.mbm GameData/Squad/Parts/Engine/liquidEnginePoodle/model001.mbmbak
mv GameData/Squad/Parts/Engine/liquidEnginePoodle/model002.mbm GameData/Squad/Parts/Engine/liquidEnginePoodle/model002.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineSkipper/Cover_CLR.mbm GameData/Squad/Parts/Engine/liquidEngineSkipper/Cover_CLR.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineSkipper/Cover_NRM.mbm GameData/Squad/Parts/Engine/liquidEngineSkipper/Cover_NRM.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineSkipper/ksp_l_midrangeEngine_diff.mbm GameData/Squad/Parts/Engine/liquidEngineSkipper/ksp_l_midrangeEngine_diff.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineSkipper/ksp_l_midrangeEngine_emissive.mbm GameData/Squad/Parts/Engine/liquidEngineSkipper/ksp_l_midrangeEngine_emissive.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineSkipper/ksp_l_midrangeEngine_normal.mbm GameData/Squad/Parts/Engine/liquidEngineSkipper/ksp_l_midrangeEngine_normal.mbmbak
mv GameData/Squad/Parts/Engine/liquidEngineSkipper/model.mu GameData/Squad/Parts/Engine/liquidEngineSkipper/model.mubak
mv GameData/Squad/Parts/Engine/solidBoosterBACC/model.mu GameData/Squad/Parts/Engine/solidBoosterBACC/model.mubak
mv GameData/Squad/Parts/Engine/solidBoosterBACC/model000.mbm GameData/Squad/Parts/Engine/solidBoosterBACC/model000.mbmbak
mv GameData/Squad/Parts/Engine/solidBoosterBACC/model001.mbm GameData/Squad/Parts/Engine/solidBoosterBACC/model001.mbmbak
mv GameData/Squad/Parts/Engine/solidBoosterBACC/model002.mbm GameData/Squad/Parts/Engine/solidBoosterBACC/model002.mbmbak
mv GameData/Squad/Parts/Engine/solidBoosterRT-10/model.mu GameData/Squad/Parts/Engine/solidBoosterRT-10/model.mubak
mv GameData/Squad/Parts/Engine/solidBoosterRT-10/model000.mbm GameData/Squad/Parts/Engine/solidBoosterRT-10/model000.mbmbak
mv GameData/Squad/Parts/Engine/solidBoosterRT-10/model001.mbm GameData/Squad/Parts/Engine/solidBoosterRT-10/model001.mbmbak
mv GameData/Squad/Parts/Engine/solidBoosterRT-10/model002.mbm GameData/Squad/Parts/Engine/solidBoosterRT-10/model002.mbmbak
mv GameData/Squad/Parts/Engine/solidBoosterSep/model.mu GameData/Squad/Parts/Engine/solidBoosterSep/model.mubak
mv GameData/Squad/Parts/Engine/solidBoosterSep/model000.mbm GameData/Squad/Parts/Engine/solidBoosterSep/model000.mbmbak
mv GameData/Squad/Parts/Engine/solidBoosterSep/model001.mbm GameData/Squad/Parts/Engine/solidBoosterSep/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankJumbo-64/model.mu GameData/Squad/Parts/FuelTank/fuelTankJumbo-64/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankJumbo-64/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankJumbo-64/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankJumbo-64/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankJumbo-64/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankOscarB/model.mu GameData/Squad/Parts/FuelTank/fuelTankOscarB/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankOscarB/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankOscarB/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankOscarB/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankOscarB/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT100/model.mu GameData/Squad/Parts/FuelTank/fuelTankT100/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankT100/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankT100/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT100/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankT100/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT100/tank4.mbm GameData/Squad/Parts/FuelTank/fuelTankT100/tank4.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT200/model.mu GameData/Squad/Parts/FuelTank/fuelTankT200/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankT200/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankT200/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT200/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankT200/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT200/tank3.mbm GameData/Squad/Parts/FuelTank/fuelTankT200/tank3.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT200/tank3_n.mbm GameData/Squad/Parts/FuelTank/fuelTankT200/tank3_n.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT400/model.mu GameData/Squad/Parts/FuelTank/fuelTankT400/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankT400/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankT400/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT400/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankT400/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT800/model.mu GameData/Squad/Parts/FuelTank/fuelTankT800/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankT800/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankT800/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankT800/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankT800/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankToroidal/model.mu GameData/Squad/Parts/FuelTank/fuelTankToroidal/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankToroidal/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankToroidal/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankToroidal/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankToroidal/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-16/model.mu GameData/Squad/Parts/FuelTank/fuelTankX200-16/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-16/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankX200-16/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-16/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankX200-16/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-32/model.mu GameData/Squad/Parts/FuelTank/fuelTankX200-32/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-32/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankX200-32/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-32/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankX200-32/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-8/model.mu GameData/Squad/Parts/FuelTank/fuelTankX200-8/model.mubak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-8/model000.mbm GameData/Squad/Parts/FuelTank/fuelTankX200-8/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/fuelTankX200-8/model001.mbm GameData/Squad/Parts/FuelTank/fuelTankX200-8/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR1/model.mu GameData/Squad/Parts/FuelTank/RCSFuelTankR1/model.mubak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR1/model000.tga GameData/Squad/Parts/FuelTank/RCSFuelTankR1/model000.tgabak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR1/model001_NRM.tga GameData/Squad/Parts/FuelTank/RCSFuelTankR1/model001_NRM.tgabak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR10/model.mu GameData/Squad/Parts/FuelTank/RCSFuelTankR10/model.mubak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR10/model000.mbm GameData/Squad/Parts/FuelTank/RCSFuelTankR10/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR10/model001.mbm GameData/Squad/Parts/FuelTank/RCSFuelTankR10/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR25/model.mu GameData/Squad/Parts/FuelTank/RCSFuelTankR25/model.mubak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR25/model000.mbm GameData/Squad/Parts/FuelTank/RCSFuelTankR25/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/RCSFuelTankR25/model001.mbm GameData/Squad/Parts/FuelTank/RCSFuelTankR25/model001.mbmbak
mv GameData/Squad/Parts/FuelTank/RCSTankRadial/model.mu GameData/Squad/Parts/FuelTank/RCSTankRadial/model.mubak
mv GameData/Squad/Parts/FuelTank/RCSTankRadial/model000.mbm GameData/Squad/Parts/FuelTank/RCSTankRadial/model000.mbmbak
mv GameData/Squad/Parts/FuelTank/RCStankRadialLong/model.mu GameData/Squad/Parts/FuelTank/RCStankRadialLong/model.mubak
mv GameData/Squad/Parts/FuelTank/RCStankRadialLong/model000.mbm GameData/Squad/Parts/FuelTank/RCStankRadialLong/model000.mbmbak
mv GameData/Squad/Parts/Mk1/mk1fuselage.mbm GameData/Squad/Parts/Mk1/mk1fuselage.mbmbak
mv GameData/Squad/Parts/Mk1/mk1fuselage.mu GameData/Squad/Parts/Mk1/mk1fuselage.mubak
mv GameData/Squad/Parts/Mk1/mk1fuselageFuel.mbm GameData/Squad/Parts/Mk1/mk1fuselageFuel.mbmbak
mv GameData/Squad/Parts/Mk1/mk1fuselageFuel_NRM.mbm GameData/Squad/Parts/Mk1/mk1fuselageFuel_NRM.mbmbak
mv GameData/Squad/Parts/Mk1/mk1fuselageIntake.mu GameData/Squad/Parts/Mk1/mk1fuselageIntake.mubak
mv GameData/Squad/Parts/Mk1/mk1fuselage_NRM.mbm GameData/Squad/Parts/Mk1/mk1fuselage_NRM.mbmbak
mv GameData/Squad/Parts/Mk1/mk1structural.mu GameData/Squad/Parts/Mk1/mk1structural.mubak
mv GameData/Squad/Parts/Mk1/model000.mbm GameData/Squad/Parts/Mk1/model000.mbmbak
mv GameData/Squad/Parts/Mk1/model001.mbm GameData/Squad/Parts/Mk1/model001.mbmbak
mv GameData/Squad/Parts/Science/avionicsNoseCone/model.mu GameData/Squad/Parts/Science/avionicsNoseCone/model.mubak
mv GameData/Squad/Parts/Science/avionicsNoseCone/model000.mbm GameData/Squad/Parts/Science/avionicsNoseCone/model000.mbmbak
mv GameData/Squad/Parts/Science/avionicsNoseCone/model001.mbm GameData/Squad/Parts/Science/avionicsNoseCone/model001.mbmbak
mv GameData/Squad/Parts/Structural/adapterSmallMiniShort/ksp_s_adapterShort_diff.mbm GameData/Squad/Parts/Structural/adapterSmallMiniShort/ksp_s_adapterShort_diff.mbmbak
mv GameData/Squad/Parts/Structural/adapterSmallMiniShort/model.mu GameData/Squad/Parts/Structural/adapterSmallMiniShort/model.mubak
mv GameData/Squad/Parts/Structural/engineBodyRadial/C1EB_NRM.mbm GameData/Squad/Parts/Structural/engineBodyRadial/C1EB_NRM.mbmbak
mv GameData/Squad/Parts/Structural/engineBodyRadial/C7A_EngineBody_F1_COLOR\ copy.mbm GameData/Squad/Parts/Structural/engineBodyRadial/C7A_EngineBody_F1_COLOR\ copy.mbmbak
mv GameData/Squad/Parts/Structural/engineBodyRadial/model.mu GameData/Squad/Parts/Structural/engineBodyRadial/model.mubak
mv GameData/Squad/Parts/Structural/engineNacelle/model.mu GameData/Squad/Parts/Structural/engineNacelle/model.mubak
mv GameData/Squad/Parts/Structural/engineNacelle/model000.mbm GameData/Squad/Parts/Structural/engineNacelle/model000.mbmbak
mv GameData/Squad/Parts/Structural/engineNacelle/model001.mbm GameData/Squad/Parts/Structural/engineNacelle/model001.mbmbak
mv GameData/Squad/Parts/Structural/smallHardpoint/model.mu GameData/Squad/Parts/Structural/smallHardpoint/model.mubak
mv GameData/Squad/Parts/Structural/smallHardpoint/model000.mbm GameData/Squad/Parts/Structural/smallHardpoint/model000.mbmbak
mv GameData/Squad/Parts/Structural/stationHub/model.mu GameData/Squad/Parts/Structural/stationHub/model.mubak
mv GameData/Squad/Parts/Structural/stationHub/model000.mbm GameData/Squad/Parts/Structural/stationHub/model000.mbmbak
mv GameData/Squad/Parts/Structural/stationHub/model001.mbm GameData/Squad/Parts/Structural/stationHub/model001.mbmbak
mv GameData/Squad/Parts/Structural/structuralIBeam200/model.mu GameData/Squad/Parts/Structural/structuralIBeam200/model.mubak
mv GameData/Squad/Parts/Structural/structuralIBeam200/model000.mbm GameData/Squad/Parts/Structural/structuralIBeam200/model000.mbmbak
mv GameData/Squad/Parts/Structural/structuralIBeam200/model001.mbm GameData/Squad/Parts/Structural/structuralIBeam200/model001.mbmbak
mv GameData/Squad/Parts/Structural/structuralIBeam200Pocket/model.mu GameData/Squad/Parts/Structural/structuralIBeam200Pocket/model.mubak
mv GameData/Squad/Parts/Structural/structuralIBeam200Pocket/model000.mbm GameData/Squad/Parts/Structural/structuralIBeam200Pocket/model000.mbmbak
mv GameData/Squad/Parts/Structural/structuralIBeam200Pocket/model001.mbm GameData/Squad/Parts/Structural/structuralIBeam200Pocket/model001.mbmbak
mv GameData/Squad/Parts/Structural/structuralIBeam650/model.mu GameData/Squad/Parts/Structural/structuralIBeam650/model.mubak
mv GameData/Squad/Parts/Structural/structuralIBeam650/model000.mbm GameData/Squad/Parts/Structural/structuralIBeam650/model000.mbmbak
mv GameData/Squad/Parts/Structural/structuralIBeam650/model001.mbm GameData/Squad/Parts/Structural/structuralIBeam650/model001.mbmbak
mv GameData/Squad/Parts/Structural/structuralMicronode/model.mu GameData/Squad/Parts/Structural/structuralMicronode/model.mubak
mv GameData/Squad/Parts/Structural/structuralMicronode/model000.mbm GameData/Squad/Parts/Structural/structuralMicronode/model000.mbmbak
mv GameData/Squad/Parts/Structural/structuralMicronode/model001.mbm GameData/Squad/Parts/Structural/structuralMicronode/model001.mbmbak
mv GameData/Squad/Parts/Structural/structuralPanel1x1/model.mu GameData/Squad/Parts/Structural/structuralPanel1x1/model.mubak
mv GameData/Squad/Parts/Structural/structuralPanel1x1/model000.mbm GameData/Squad/Parts/Structural/structuralPanel1x1/model000.mbmbak
mv GameData/Squad/Parts/Structural/structuralPanel1x1/model001.mbm GameData/Squad/Parts/Structural/structuralPanel1x1/model001.mbmbak
mv GameData/Squad/Parts/Structural/structuralPanel2x2/model.mu GameData/Squad/Parts/Structural/structuralPanel2x2/model.mubak
mv GameData/Squad/Parts/Structural/structuralPanel2x2/model000.mbm GameData/Squad/Parts/Structural/structuralPanel2x2/model000.mbmbak
mv GameData/Squad/Parts/Structural/structuralPanel2x2/model001.mbm GameData/Squad/Parts/Structural/structuralPanel2x2/model001.mbmbak
mv GameData/Squad/Parts/Structural/structuralPylon/model.mu GameData/Squad/Parts/Structural/structuralPylon/model.mubak
mv GameData/Squad/Parts/Structural/strutCubicOcto/model.mu GameData/Squad/Parts/Structural/strutCubicOcto/model.mubak
mv GameData/Squad/Parts/Structural/strutCubicOcto/model000.mbm GameData/Squad/Parts/Structural/strutCubicOcto/model000.mbmbak
mv GameData/Squad/Parts/Structural/trussGirderAdapter/model.mu GameData/Squad/Parts/Structural/trussGirderAdapter/model.mubak
mv GameData/Squad/Parts/Structural/trussGirderAdapter/model000.mbm GameData/Squad/Parts/Structural/trussGirderAdapter/model000.mbmbak
mv GameData/Squad/Parts/Structural/trussGirderAdapter/model001.mbm GameData/Squad/Parts/Structural/trussGirderAdapter/model001.mbmbak
mv GameData/Squad/Parts/Structural/trussGirderL/model.mu GameData/Squad/Parts/Structural/trussGirderL/model.mubak
mv GameData/Squad/Parts/Structural/trussGirderL/model000.mbm GameData/Squad/Parts/Structural/trussGirderL/model000.mbmbak
mv GameData/Squad/Parts/Structural/trussGirderL/model001.mbm GameData/Squad/Parts/Structural/trussGirderL/model001.mbmbak
mv GameData/Squad/Parts/Structural/trussGirderXL/model.mu GameData/Squad/Parts/Structural/trussGirderXL/model.mubak
mv GameData/Squad/Parts/Structural/trussGirderXL/model000.mbm GameData/Squad/Parts/Structural/trussGirderXL/model000.mbmbak
mv GameData/Squad/Parts/Structural/trussGirderXL/model001.mbm GameData/Squad/Parts/Structural/trussGirderXL/model001.mbmbak
mv GameData/Squad/Parts/Utility/CircularIntake/model.mu GameData/Squad/Parts/Utility/CircularIntake/model.mubak
mv GameData/Squad/Parts/Utility/CircularIntake/model000.mbm GameData/Squad/Parts/Utility/CircularIntake/model000.mbmbak
mv GameData/Squad/Parts/Utility/commsDish16/model.mu GameData/Squad/Parts/Utility/commsDish16/model.mubak
mv GameData/Squad/Parts/Utility/commsDish16/model000.mbm GameData/Squad/Parts/Utility/commsDish16/model000.mbmbak
mv GameData/Squad/Parts/Utility/decouplerSeparatorTR-2C/model.mu GameData/Squad/Parts/Utility/decouplerSeparatorTR-2C/model.mubak
mv GameData/Squad/Parts/Utility/decouplerSeparatorTR-2C/model000.mbm GameData/Squad/Parts/Utility/decouplerSeparatorTR-2C/model000.mbmbak
mv GameData/Squad/Parts/Utility/decouplerSeparatorTR-2C/model001.mbm GameData/Squad/Parts/Utility/decouplerSeparatorTR-2C/model001.mbmbak
mv GameData/Squad/Parts/Utility/decouplerStack2m/model.mu GameData/Squad/Parts/Utility/decouplerStack2m/model.mubak
mv GameData/Squad/Parts/Utility/decouplerStack2m/model000.mbm GameData/Squad/Parts/Utility/decouplerStack2m/model000.mbmbak
mv GameData/Squad/Parts/Utility/decouplerStack2m/model001.mbm GameData/Squad/Parts/Utility/decouplerStack2m/model001.mbmbak
mv GameData/Squad/Parts/Utility/decouplerStackTR-18A/model.mu GameData/Squad/Parts/Utility/decouplerStackTR-18A/model.mubak
mv GameData/Squad/Parts/Utility/decouplerStackTR-18A/model000.mbm GameData/Squad/Parts/Utility/decouplerStackTR-18A/model000.mbmbak
mv GameData/Squad/Parts/Utility/decouplerStackTR-18A/model001.mbm GameData/Squad/Parts/Utility/decouplerStackTR-18A/model001.mbmbak
mv GameData/Squad/Parts/Utility/decouplerStackTR-2V/model.mu GameData/Squad/Parts/Utility/decouplerStackTR-2V/model.mubak
mv GameData/Squad/Parts/Utility/decouplerStackTR-2V/model000.mbm GameData/Squad/Parts/Utility/decouplerStackTR-2V/model000.mbmbak
mv GameData/Squad/Parts/Utility/decouplerStackTR-2V/model001.mbm GameData/Squad/Parts/Utility/decouplerStackTR-2V/model001.mbmbak
mv GameData/Squad/Parts/Utility/dockingPort/model.mu GameData/Squad/Parts/Utility/dockingPort/model.mubak
mv GameData/Squad/Parts/Utility/dockingPort/model000.mbm GameData/Squad/Parts/Utility/dockingPort/model000.mbmbak
mv GameData/Squad/Parts/Utility/dockingPort/model001.mbm GameData/Squad/Parts/Utility/dockingPort/model001.mbmbak
mv GameData/Squad/Parts/Utility/dockingPort/model002.mbm GameData/Squad/Parts/Utility/dockingPort/model002.mbmbak
mv GameData/Squad/Parts/Utility/dockingPortInline/model.mu GameData/Squad/Parts/Utility/dockingPortInline/model.mubak
mv GameData/Squad/Parts/Utility/dockingPortInline/model000.mbm GameData/Squad/Parts/Utility/dockingPortInline/model000.mbmbak
mv GameData/Squad/Parts/Utility/dockingPortInline/model001.mbm GameData/Squad/Parts/Utility/dockingPortInline/model001.mbmbak
mv GameData/Squad/Parts/Utility/dockingPortInline/model003.mbm GameData/Squad/Parts/Utility/dockingPortInline/model003.mbmbak
mv GameData/Squad/Parts/Utility/dockingPortJr/model.mu GameData/Squad/Parts/Utility/dockingPortJr/model.mubak
mv GameData/Squad/Parts/Utility/dockingPortJr/model000.mbm GameData/Squad/Parts/Utility/dockingPortJr/model000.mbmbak
mv GameData/Squad/Parts/Utility/dockingPortJr/model001.mbm GameData/Squad/Parts/Utility/dockingPortJr/model001.mbmbak
mv GameData/Squad/Parts/Utility/fuelLine/model000.mbm GameData/Squad/Parts/Utility/fuelLine/model000.mbmbak
mv GameData/Squad/Parts/Utility/largeAdapter/model.mu GameData/Squad/Parts/Utility/largeAdapter/model.mubak
mv GameData/Squad/Parts/Utility/largeAdapter/model000.mbm GameData/Squad/Parts/Utility/largeAdapter/model000.mbmbak
mv GameData/Squad/Parts/Utility/largeAdapterShort/model.mu GameData/Squad/Parts/Utility/largeAdapterShort/model.mubak
mv GameData/Squad/Parts/Utility/largeAdapterShort/model000.mbm GameData/Squad/Parts/Utility/largeAdapterShort/model000.mbmbak
mv GameData/Squad/Parts/Utility/linearRCS/LInRCS_CLR.tga GameData/Squad/Parts/Utility/linearRCS/LInRCS_CLR.tgabak
mv GameData/Squad/Parts/Utility/linearRCS/model.mu GameData/Squad/Parts/Utility/linearRCS/model.mubak
mv GameData/Squad/Parts/Utility/linearRCS/model000.mbm GameData/Squad/Parts/Utility/linearRCS/model000.mbmbak
mv GameData/Squad/Parts/Utility/linearRCS/model001.mbm GameData/Squad/Parts/Utility/linearRCS/model001.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk1/model.mu GameData/Squad/Parts/Utility/parachuteMk1/model.mubak
mv GameData/Squad/Parts/Utility/parachuteMk1/model000.mbm GameData/Squad/Parts/Utility/parachuteMk1/model000.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk1/model001.mbm GameData/Squad/Parts/Utility/parachuteMk1/model001.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk1/Parachute.mbm GameData/Squad/Parts/Utility/parachuteMk1/Parachute.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk1/Parachute_NRM.mbm GameData/Squad/Parts/Utility/parachuteMk1/Parachute_NRM.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk16-XL/model.mu GameData/Squad/Parts/Utility/parachuteMk16-XL/model.mubak
mv GameData/Squad/Parts/Utility/parachuteMk16-XL/model000.mbm GameData/Squad/Parts/Utility/parachuteMk16-XL/model000.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk16-XL/model001.mbm GameData/Squad/Parts/Utility/parachuteMk16-XL/model001.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk16-XL/Parachute.mbm GameData/Squad/Parts/Utility/parachuteMk16-XL/Parachute.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk16-XL/Parachute_NRM.mbm GameData/Squad/Parts/Utility/parachuteMk16-XL/Parachute_NRM.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk2-R/model.mu GameData/Squad/Parts/Utility/parachuteMk2-R/model.mubak
mv GameData/Squad/Parts/Utility/parachuteMk2-R/model000.mbm GameData/Squad/Parts/Utility/parachuteMk2-R/model000.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk2-R/Parachute.mbm GameData/Squad/Parts/Utility/parachuteMk2-R/Parachute.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk2-R/Parachute_NRM.mbm GameData/Squad/Parts/Utility/parachuteMk2-R/Parachute_NRM.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk25/model.mu GameData/Squad/Parts/Utility/parachuteMk25/model.mubak
mv GameData/Squad/Parts/Utility/parachuteMk25/model000.mbm GameData/Squad/Parts/Utility/parachuteMk25/model000.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk25/model001.mbm GameData/Squad/Parts/Utility/parachuteMk25/model001.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk25/Parachute.mbm GameData/Squad/Parts/Utility/parachuteMk25/Parachute.mbmbak
mv GameData/Squad/Parts/Utility/parachuteMk25/Parachute_NRM.mbm GameData/Squad/Parts/Utility/parachuteMk25/Parachute_NRM.mbmbak
mv GameData/Squad/Parts/Utility/rcsBlockRV-105/model.mu GameData/Squad/Parts/Utility/rcsBlockRV-105/model.mubak
mv GameData/Squad/Parts/Utility/rcsBlockRV-105/model000.mbm GameData/Squad/Parts/Utility/rcsBlockRV-105/model000.mbmbak
mv GameData/Squad/Parts/Utility/sensorAccelerometer/model.mu GameData/Squad/Parts/Utility/sensorAccelerometer/model.mubak
mv GameData/Squad/Parts/Utility/sensorAccelerometer/model000.mbm GameData/Squad/Parts/Utility/sensorAccelerometer/model000.mbmbak
mv GameData/Squad/Parts/Utility/sensorBarometer/Glass.mbm GameData/Squad/Parts/Utility/sensorBarometer/Glass.mbmbak
mv GameData/Squad/Parts/Utility/sensorBarometer/model.mu GameData/Squad/Parts/Utility/sensorBarometer/model.mubak
mv GameData/Squad/Parts/Utility/sensorBarometer/model000.mbm GameData/Squad/Parts/Utility/sensorBarometer/model000.mbmbak
mv GameData/Squad/Parts/Utility/sensorGravimeter/model.mu GameData/Squad/Parts/Utility/sensorGravimeter/model.mubak
mv GameData/Squad/Parts/Utility/sensorGravimeter/model000.mbm GameData/Squad/Parts/Utility/sensorGravimeter/model000.mbmbak
mv GameData/Squad/Parts/Utility/sensorThermometer/lense.mbm GameData/Squad/Parts/Utility/sensorThermometer/lense.mbmbak
mv GameData/Squad/Parts/Utility/sensorThermometer/model.mu GameData/Squad/Parts/Utility/sensorThermometer/model.mubak
mv GameData/Squad/Parts/Utility/sensorThermometer/Therm-CLR.mbm GameData/Squad/Parts/Utility/sensorThermometer/Therm-CLR.mbmbak
mv GameData/Squad/SPP/Wings/Wings.mbm GameData/Squad/SPP/Wings/Wings.mbmbak
cp GameData/VenStockRevamp/Squad/Parts/Electrical/radialFlatSolarPanel/model000.mbm GameData/Squad/SPP/Wings/Wings.mbm