mv "GameData\Squad\Parts\Command\advancedSasModuleLarge\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\advancedSasModuleLarge\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\advancedSasModuleLarge\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\inlineAdvancedStabilizer\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\inlineAdvancedStabilizer\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\inlineAdvancedStabilizer\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\inlineReactionWheel\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\inlineReactionWheel\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\inlineReactionWheel\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\inlineReactionWheel\model002.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Command\Mk1-2Pod\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\Mk1-2Pod\ladder.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch NRM.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\Mk1-2Pod\walls.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\Mk1-2Pod\window.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk1Cockpit\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\mk1Cockpit\mk1Cockpit.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk1pod\model.mu.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk1pod\hatch.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk1pod\ladderrung.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk1pod\outer shell NRM.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk1pod\outer shell.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk1pod\window.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk2LanderCan\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\mk2LanderCan\ladder.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk2LanderCan\outershell.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk2LanderCan\outershell_n.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\mk2LanderCan\window.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\hitchhikerStorageContainer\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin_n.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\hitchhikerStorageContainer\window.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Command\probeCoreCube\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\probeCoreCube\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeCoreCube\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeCoreHex\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\probeCoreHex\ksp_m_hexProbe_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeCoreHex\ksp_m_hexProbe_normal.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeCoreOcto\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\probeCoreOcto\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeCoreOcto\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeCoreOcto2\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\probeCoreOcto2\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeStackSphere\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Command\probeStackSphere\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Command\probeStackSphere\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\CompoundParts\fuelLine\model.mu.bak" *.mu
mv "GameData\Squad\Parts\CompoundParts\fuelLine\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\CompoundParts\strutConnector\model.mu.bak" *.mu
mv "GameData\Squad\Parts\CompoundParts\strutConnector\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineMk55\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineMk55\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\solidBoosterRT-10\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\solidBoosterRT-10\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\solidBoosterRT-10\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\solidBoosterRT-10\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model003.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model004.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model003.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngine48-7S\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngine48-7S\ksp_m_liquidEngine_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngine48-7S\ksp_m_liquidEngine_norm.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngine48-7S\ksp_m_liquidFuelEngine_fairing_norm.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngine48-7S\ksp_m_liquidFuelEngine_fairing_psd.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-1\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineLV-1\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-1\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngine24-77\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngine24-77\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-1R\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineLV-1R\ksp_r_microEngine_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-909\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineLV-909\bigfairing.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-909\engine3.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-909\engine3_emissive.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-909\engine3_n.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineSkipper\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_emissive.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_fairing_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_fairing_norm.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_normal.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Engine\OMSEngine\NewModel.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\OMSEngine\engineoms 1.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\OMSEngine\engineomsN_NRM.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Engine\liquidEngineAerospike\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineAerospike\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineAerospike\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineAerospike\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineMainsail\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineMainsail\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineMainsail\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineMainsail\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineMainsail\model003.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineMainsail\model004.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\solidBoosterSep\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\solidBoosterSep\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-N\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEngineLV-N\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-N\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-N\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEngineLV-N\model003.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEnginePoodle\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\liquidEnginePoodle\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEnginePoodle\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEnginePoodle\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\liquidEnginePoodle\model003.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\jetEngineBasic\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\jetEngineBasic\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\jetEngineBasic\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\jetEngineTurbo\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\jetEngineTurbo\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\jetEngineTurbo\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\solidBoosterBACC\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Engine\solidBoosterBACC\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\solidBoosterBACC\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Engine\solidBoosterBACC\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralPylon\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\structuralPylon\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralPylon\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPort\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\dockingPort\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPort\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortJr\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\dockingPortJr\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortJr\model001.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Utility\dockingPortShielded\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\dockingPortShielded\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortShielded\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortShielded\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortSr\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\dockingPortSr\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortSr\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\radialAttachmentPoint\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\radialAttachmentPoint\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\radialAttachmentPoint\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\ladderRadial\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\ladderRadial\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\ladderRadial\model001.mbm.bak" *.mbm

mv "GameData\Squad\Parts\FuelTank\fuelTankX200-8\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-8\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-8\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-16\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-16\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-16\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankT100\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankT100\tank4.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankT200\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankT200\tank3.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankT200\tank3_n.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankT400\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankT400\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankT400\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR10\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR10\ksp_m_rcsTank_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR10\ksp_m_rcsTank_normal.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\RCSTankRadial\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\RCSTankRadial\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\RCStankRadialLong\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\RCStankRadialLong\ksp_r_rcsCylTank_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankOscarB\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankOscarB\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankOscarB\model001.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Structural\LargeCrewedLab\large_crewed_lab.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\LargeCrewedLab\Large_Crewed_Lab.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\LargeCrewedLab\window.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Structural\adapterSmallMiniShort\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\adapterSmallMiniShort\ksp_s_adapterShort_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralPanel1x1\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\structuralPanel1x1\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralPanel1x1\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralMicronode\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\structuralMicronode\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\trussGirderAdapter\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\trussGirderAdapter\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\trussGirderAdapter\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\trussGirderL\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\trussGirderL\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\trussGirderXL\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\trussGirderXL\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralIBeam200\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\structuralIBeam200\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralIBeam650\modelv.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\structuralIBeam650\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralIBeam200Pocket\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\structuralIBeam200Pocket\model000.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Utility\decouplerRadialHDM\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerRadialHDM\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerRadialTT-38K\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerRadialTT-38K\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerRadialTT-70\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerRadialTT-70\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerSeparatorTR-18D\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerSeparatorTR-18D\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerSeparatorTR-18D\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerSeparatorTR-XL\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerSeparatorTR-XL\model000.mbm.bak" *.mbm

mv "GameData\Squad\Parts\Utility\decouplerSeparatorTR-2C\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerSeparatorTR-2C\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerStackTR-2V\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerStackTR-2V\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk2-R\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\parachuteMk2-R\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk2-R\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk16-XL\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\parachuteMk16-XL\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk16-XL\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk1\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\parachuteMk1\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk1\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk25\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\parachuteMk25\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\parachuteMk25\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\2x3ShroudSolarPanels\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\2x3ShroudSolarPanels\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\2x3ShroudSolarPanels\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\2x3ShroudSolarPanels\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\2x3SolarPanels\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\2x3SolarPanels\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\2x3SolarPanels\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\2x3SolarPanels\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\1x6SolarPanels\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\1x6SolarPanels\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\1x6SolarPanels\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\1x6SolarPanels\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\radialFlatSolarPanel\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\radialFlatSolarPanel\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\gigantorXlSolarArray\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\gigantorXlSolarArray\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\RTG\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\RTG\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\z-1kBattery\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\z-1kBattery\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\z-1kBattery\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\z-200Battery\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\z-200Battery\ksp_m_batteryPack_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\z-400Battery\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\z-400Battery\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\z-100Battery\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\z-100Battery\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\z-4kBattery\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Electrical\z-4kBattery\ksp_l_batteryPack_diff.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Electrical\z-4kBattery\ksp_l_batteryPack_normal.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\spotLightMk1\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\spotLightMk1\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\spotLightMk1\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\spotLightMk2\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\spotLightMk2\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\spotLightMk2\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\standardNoseCone\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\standardNoseCone\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\standardNoseCone\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\advancedCanard\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\advancedCanard\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\advancedCanard\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\aerodynamicNoseCone\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\aerodynamicNoseCone\Nosecone.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\noseConeAdapter\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\noseConeAdapter\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\noseConeAdapter\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\protectiveRocketNoseMk7\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\protectiveRocketNoseMk7\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\standardCanard\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\standardCanard\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\standardCanard\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\sweptWing\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\sweptWing\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\sweptWing\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\sweptWing\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\tailConnector\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\tailConnector\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\tailConnector\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\tailfin\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\tailfin\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\tailfin\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\wingletAV-R8\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\wingletAV-R8\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\wingletAV-R8\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Aero\wingletDeltaDeluxe\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Aero\wingletDeltaDeluxe\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankJumbo-64\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankJumbo-64\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankJumbo-64\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankT800\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankT800\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankT800\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankToroidal\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankToroidal\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankToroidal\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-32\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-32\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\fuelTankX200-32\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR1\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR1\model000.tga.bak" *.tga
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR1\model001.tga.bak" *.tga
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR25\model.mu.bak" *.mu
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR25\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\FuelTank\RCSFuelTankR25\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Mk1\mk1fuselage.mu.bak" *.mu
mv "GameData\Squad\Parts\Mk1\mk1fuselageIntake.mu.bak" *.mu
mv "GameData\Squad\Parts\Mk1\mk1structural.mu.bak" *.mu
mv "GameData\Squad\Parts\Mk1\mk1fuselage.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Mk1\mk1fuselageFuel.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Science\avionicsNoseCone\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Science\avionicsNoseCone\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\engineBodyRadial\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\engineBodyRadial\C1EB_NRM.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\engineBodyRadial\C7A_EngineBody_F1_COLOR copy.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\engineNacelle\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\engineNacelle\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\engineNacelle\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\smallHardpoint\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\smallHardpoint\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\smallHardpoint\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\stationHub\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\stationHub\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\stationHub\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralPanel2x2\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Structural\structuralPanel2x2\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\structuralPanel2x2\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Structural\strutCubicOcto\model.mu.bak" *.muv
mv "GameData\Squad\Parts\Structural\strutCubicOcto\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\CircularIntake\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\CircularIntake\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\CircularIntake\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\commsDish16\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\commsDish16\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerStack2m\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerStack2m\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerStack2m\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerStackTR-18A\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\decouplerStackTR-18A\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\decouplerStackTR-18A\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortInline\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\dockingPortInline\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortInline\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\dockingPortInline\model002.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\largeAdapter\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\largeAdapter\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\largeAdapterShort\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\largeAdapterShort\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\linearRCS\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\linearRCS\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\linearRCS\model001.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\rcsBlockRV-105\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\rcsBlockRV-105\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\sensorAccelerometer\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\sensorAccelerometer\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\sensorBarometer\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\sensorBarometer\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\sensorGravimeter\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\sensorGravimeter\model000.mbm.bak" *.mbm
mv "GameData\Squad\Parts\Utility\sensorThermometer\model.mu.bak" *.mu
mv "GameData\Squad\Parts\Utility\sensorThermometer\model000.mbm.bak" *.mbm
