ren "GameData\Squad\Parts\Aero\advancedCanard\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\advancedCanard\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\aerodynamicNoseCone\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\aerodynamicNoseCone\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\noseConeAdapter\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\noseConeAdapter\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\noseConeAdapter\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\protectiveRocketNoseMk7\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\protectiveRocketNoseMk7\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\standardCanard\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\standardCanard\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\standardCanard\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\standardNoseCone\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\standardNoseCone\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\standardNoseCone\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\sweptWing\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\sweptWing\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\sweptWing\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\tailConnector\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\tailConnector\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\tailfin\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\tailfin\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\tailfin\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Aero\wingletAV-R8\model.mu" *.mubak
ren "GameData\Squad\Parts\Aero\wingletAV-R8\model000.tga" *.tgabak
ren "GameData\Squad\Parts\Aero\wingletAV-R8\model001.tga" *.tgabak
ren "GameData\Squad\Parts\Aero\wingletAV-R8\model002_NRM.tga" *.tgabak
ren "GameData\Squad\Parts\Aero\wingletDeltaDeluxe\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin_LUM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin_n.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\hitchhikerStorageContainer\model.mu" *.mubak
ren "GameData\Squad\Parts\Command\Mk1-2Pod\ladder.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\Mk1-2Pod\model.mu" *.mubak
ren "GameData\Squad\Parts\Command\mk1Cockpit\mk1Cockpit.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk1Cockpit\mk1cockpit_LUM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk1Cockpit\mk1cockpit_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk1Cockpit\model.mu" *.mubak
ren "GameData\Squad\Parts\Command\mk1pod\hatch.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk1pod\model.mu" *.mubak
ren "GameData\Squad\Parts\Command\mk1pod\outer shell NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk1pod\outer shell.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk2LanderCan\ladder.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk2LanderCan\model.mu" *.mubak
ren "GameData\Squad\Parts\Command\mk2LanderCan\outershell.mbm" *.mbmbak
ren "GameData\Squad\Parts\Command\mk2LanderCan\outershell_n.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\1x6ShroudSolarPanels\SHieldbox_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\1x6SolarPanels\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\1x6SolarPanels\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\1x6SolarPanels\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\gigantorXlSolarArray\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\gigantorXlSolarArray\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\gigantorXlSolarArray\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\radialFlatSolarPanel\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\radialFlatSolarPanel\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\radialFlatSolarPanel\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\RTG\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\RTG\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-100Battery\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\z-100Battery\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-1kBattery\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\z-1kBattery\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-1kBattery\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-200Battery\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\z-200Battery\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-200Battery\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-400Battery\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\z-400Battery\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-4kBattery\model.mu" *.mubak
ren "GameData\Squad\Parts\Electrical\z-4kBattery\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Electrical\z-4kBattery\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\jetEngineBasic\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\jetEngineBasic\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\jetEngineBasic\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\jetEngineBasic\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\jetEngineTurbo\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\jetEngineTurbo\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\jetEngineTurbo\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\jetEngineTurbo\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineAerospike\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineAerospike\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineAerospike\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEngineAerospike\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineAerospike\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineAerospike\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineAerospike\model003.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-909\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-909\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-909\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-909\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-909\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-909\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-N\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-N\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-N\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-N\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-N\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-N\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T30\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T30\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T30\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T45\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T45\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineLV-T45\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMainsail\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMainsail\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMainsail\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEngineMainsail\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMainsail\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMainsail\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMk55\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEngineMk55\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMk55\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineMk55\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEnginePoodle\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEnginePoodle\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEnginePoodle\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\liquidEnginePoodle\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEnginePoodle\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEnginePoodle\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineSkipper\Cover_CLR.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineSkipper\Cover_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_diff.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_emissive.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineSkipper\ksp_l_midrangeEngine_normal.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\liquidEngineSkipper\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\solidBoosterBACC\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\solidBoosterBACC\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\solidBoosterBACC\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\solidBoosterBACC\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\solidBoosterRT-10\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\solidBoosterRT-10\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\solidBoosterRT-10\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\solidBoosterRT-10\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\solidBoosterSep\model.mu" *.mubak
ren "GameData\Squad\Parts\Engine\solidBoosterSep\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Engine\solidBoosterSep\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankJumbo-64\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankJumbo-64\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankJumbo-64\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankOscarB\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankOscarB\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankOscarB\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT100\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankT100\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT100\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT100\tank4.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT200\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankT200\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT200\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT200\tank3.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT200\tank3_n.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT400\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankT400\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT400\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT800\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankT800\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankT800\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankToroidal\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankToroidal\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankToroidal\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-16\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-16\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-16\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-32\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-32\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-32\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-8\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-8\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\fuelTankX200-8\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR1\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR1\model000.tga" *.tgabak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR1\model001_NRM.tga" *.tgabak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR10\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR10\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR10\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR25\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR25\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\RCSFuelTankR25\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\RCSTankRadial\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\RCSTankRadial\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\FuelTank\RCStankRadialLong\model.mu" *.mubak
ren "GameData\Squad\Parts\FuelTank\RCStankRadialLong\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Mk1\mk1fuselage.mbm" *.mbmbak
ren "GameData\Squad\Parts\Mk1\mk1fuselage.mu" *.mubak
ren "GameData\Squad\Parts\Mk1\mk1fuselageFuel.mbm" *.mbmbak
ren "GameData\Squad\Parts\Mk1\mk1fuselageFuel_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Mk1\mk1fuselageIntake.mu" *.mubak
ren "GameData\Squad\Parts\Mk1\mk1fuselage_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Mk1\mk1structural.mu" *.mubak
ren "GameData\Squad\Parts\Mk1\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Mk1\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Science\avionicsNoseCone\model.mu" *.mubak
ren "GameData\Squad\Parts\Science\avionicsNoseCone\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Science\avionicsNoseCone\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\adapterSmallMiniShort\ksp_s_adapterShort_diff.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\adapterSmallMiniShort\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\engineBodyRadial\C1EB_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\engineBodyRadial\C7A_EngineBody_F1_COLOR copy.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\engineBodyRadial\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\engineNacelle\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\engineNacelle\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\engineNacelle\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\smallHardpoint\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\smallHardpoint\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\stationHub\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\stationHub\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\stationHub\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralIBeam200\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\structuralIBeam200\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralIBeam200\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralIBeam200Pocket\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\structuralIBeam200Pocket\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralIBeam200Pocket\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralIBeam650\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\structuralIBeam650\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralIBeam650\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralMicronode\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\structuralMicronode\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralMicronode\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralPanel1x1\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\structuralPanel1x1\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralPanel1x1\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralPanel2x2\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\structuralPanel2x2\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralPanel2x2\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\structuralPylon\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\strutCubicOcto\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\strutCubicOcto\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\trussGirderAdapter\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\trussGirderAdapter\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\trussGirderAdapter\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\trussGirderL\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\trussGirderL\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\trussGirderL\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\trussGirderXL\model.mu" *.mubak
ren "GameData\Squad\Parts\Structural\trussGirderXL\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Structural\trussGirderXL\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\CircularIntake\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\CircularIntake\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\commsDish16\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\commsDish16\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerSeparatorTR-2C\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\decouplerSeparatorTR-2C\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerSeparatorTR-2C\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerStack2m\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\decouplerStack2m\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerStack2m\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerStackTR-18A\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\decouplerStackTR-18A\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerStackTR-18A\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerStackTR-2V\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\decouplerStackTR-2V\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\decouplerStackTR-2V\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPort\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\dockingPort\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPort\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPort\model002.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPortInline\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\dockingPortInline\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPortInline\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPortInline\model003.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPortJr\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\dockingPortJr\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\dockingPortJr\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\fuelLine\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\largeAdapter\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\largeAdapter\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\largeAdapterShort\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\largeAdapterShort\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\linearRCS\LInRCS_CLR.tga" *.tgabak
ren "GameData\Squad\Parts\Utility\linearRCS\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\linearRCS\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\linearRCS\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk1\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\parachuteMk1\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk1\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk1\Parachute.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk1\Parachute_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk16-XL\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\parachuteMk16-XL\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk16-XL\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk16-XL\Parachute.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk16-XL\Parachute_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk2-R\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\parachuteMk2-R\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk2-R\Parachute.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk2-R\Parachute_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk25\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\parachuteMk25\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk25\model001.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk25\Parachute.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\parachuteMk25\Parachute_NRM.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\rcsBlockRV-105\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\rcsBlockRV-105\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\sensorAccelerometer\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\sensorAccelerometer\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\sensorBarometer\Glass.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\sensorBarometer\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\sensorBarometer\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\sensorGravimeter\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\sensorGravimeter\model000.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\sensorThermometer\lense.mbm" *.mbmbak
ren "GameData\Squad\Parts\Utility\sensorThermometer\model.mu" *.mubak
ren "GameData\Squad\Parts\Utility\sensorThermometer\Therm-CLR.mbm" *.mbmbak
ren "GameData\Squad\SPP\Wings\Wings.mbm" *.mbmbak
