#!/bin/sh
mv "../GameData/Squad/Parts/Command/Mk1-2Pod/model.mu.bak" "../GameData/Squad/Parts/Command/Mk1-2Pod/model.mu"
mv "../GameData/Squad/Parts/Command/Mk1-2Pod/ladder.dds.bak" "../GameData/Squad/Parts/Command/Mk1-2Pod/ladder.dds"
mv "../GameData/Squad/Parts/Command/Mk1-2Pod/mk 1-2 external shell Variant-Hatch NRM.dds.bak" "../GameData/Squad/Parts/Command/Mk1-2Pod/mk 1-2 external shell Variant-Hatch NRM.dds"
mv "../GameData/Squad/Parts/Command/Mk1-2Pod/mk 1-2 external shell Variant-Hatch.dds.bak" "../GameData/Squad/Parts/Command/Mk1-2Pod/mk 1-2 external shell Variant-Hatch.dds"
mv "../GameData/Squad/Parts/Command/Mk1-2Pod/walls.dds.bak" "../GameData/Squad/Parts/Command/Mk1-2Pod/walls.dds"
mv "../GameData/Squad/Parts/Command/Mk1-2Pod/window.dds.bak" "../GameData/Squad/Parts/Command/Mk1-2Pod/window.dds"
mv "../GameData/Squad/Parts/Command/mk1Cockpit/model.mu.bak" "../GameData/Squad/Parts/Command/mk1Cockpit/model.mu"
mv "../GameData/Squad/Parts/Command/mk1Cockpit/mk1Cockpit.dds.bak" "../GameData/Squad/Parts/Command/mk1Cockpit/mk1Cockpit.dds"
mv "../GameData/Squad/Parts/Command/mk1pod/model.mu.bak" "../GameData/Squad/Parts/Command/mk1pod/model.mu"
mv "../GameData/Squad/Parts/Command/mk1pod/hatch.dds.bak" "../GameData/Squad/Parts/Command/mk1pod/hatch.dds"
mv "../GameData/Squad/Parts/Command/mk1pod/ladderrung.dds.bak" "../GameData/Squad/Parts/Command/mk1pod/ladderrung.dds"
mv "../GameData/Squad/Parts/Command/mk1pod/outer shell NRM.dds.bak" "../GameData/Squad/Parts/Command/mk1pod/outer shell NRM.dds"
mv "../GameData/Squad/Parts/Command/mk1pod/outer shell.dds.bak" "../GameData/Squad/Parts/Command/mk1pod/outer shell.dds"
mv "../GameData/Squad/Parts/Command/mk1pod/window.dds.bak" "../GameData/Squad/Parts/Command/mk1pod/window.dds"
mv "../GameData/Squad/Parts/Command/cupola/model.mu.bak" "../GameData/Squad/Parts/Command/cupola/model.mu"
mv "../GameData/Squad/Parts/Command/cupola/ksp_l_cupola_diff.dds.bak" "../GameData/Squad/Parts/Command/cupola/ksp_l_cupola_diff.dds"
mv "../GameData/Squad/Parts/Command/cupola/ksp_l_cupola_normal.dds.bak" "../GameData/Squad/Parts/Command/cupola/ksp_l_cupola_normal.dds"
mv "../GameData/Squad/Parts/Command/cupola/window.dds.bak" "../GameData/Squad/Parts/Command/cupola/window.dds"
mv "../GameData/Squad/Parts/Command/mk2LanderCan/model.mu.bak" "../GameData/Squad/Parts/Command/mk2LanderCan/model.mu"
mv "../GameData/Squad/Parts/Command/mk2LanderCan/ladder.dds.bak" "../GameData/Squad/Parts/Command/mk2LanderCan/ladder.dds"
mv "../GameData/Squad/Parts/Command/mk2LanderCan/outershell.dds.bak" "../GameData/Squad/Parts/Command/mk2LanderCan/outershell.dds"
mv "../GameData/Squad/Parts/Command/mk2LanderCan/outershell_n.dds.bak" "../GameData/Squad/Parts/Command/mk2LanderCan/outershell_n.dds"
mv "../GameData/Squad/Parts/Command/mk2LanderCan/window.dds.bak" "../GameData/Squad/Parts/Command/mk2LanderCan/window.dds"
mv "../GameData/Squad/Parts/Command/mk1LanderCan/model.mu.bak" "../GameData/Squad/Parts/Command/mk1LanderCan/model.mu"
mv "../GameData/Squad/Parts/Command/mk1LanderCan/ksp_s_landerCan_diff.dds.bak" "../GameData/Squad/Parts/Command/mk1LanderCan/ksp_s_landerCan_diff.dds"
mv "../GameData/Squad/Parts/Command/mk1LanderCan/ksp_s_landerCan_normal.dds.bak" "../GameData/Squad/Parts/Command/mk1LanderCan/ksp_s_landerCan_normal.dds"
mv "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/model.mu.bak" "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/model.mu"
mv "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin.dds.bak" "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin.dds"
mv "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin_n.dds.bak" "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/cabin_n.dds"
mv "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/window.dds.bak" "../GameData/Squad/Parts/Command/hitchhikerStorageContainer/window.dds"
mv "../GameData/Squad/Parts/Command/probeStackSphere/model.mu.bak" "../GameData/Squad/Parts/Command/probeStackSphere/model.mu"
mv "../GameData/Squad/Parts/Command/probeStackSphere/model000.dds.bak" "../GameData/Squad/Parts/Command/probeStackSphere/model000.dds"
mv "../GameData/Squad/Parts/Command/probeStackSphere/model001.dds.bak" "../GameData/Squad/Parts/Command/probeStackSphere/model001.dds"
mv "../GameData/Squad/Parts/Command/probeCoreOcto2/model.mu.bak" "../GameData/Squad/Parts/Command/probeCoreOcto2/model.mu"
mv "../GameData/Squad/Parts/Command/probeCoreOcto2/model000.dds.bak" "../GameData/Squad/Parts/Command/probeCoreOcto2/model000.dds"
mv "../GameData/Squad/Parts/Command/probeCoreOcto/model.mu.bak" "../GameData/Squad/Parts/Command/probeCoreOcto/model.mu"
mv "../GameData/Squad/Parts/Command/probeCoreOcto/model000.dds.bak" "../GameData/Squad/Parts/Command/probeCoreOcto/model000.dds"
mv "../GameData/Squad/Parts/Command/probeCoreOcto/model001.dds.bak" "../GameData/Squad/Parts/Command/probeCoreOcto/model001.dds"
mv "../GameData/Squad/Parts/Command/probeCoreCube/model.mu.bak" "../GameData/Squad/Parts/Command/probeCoreCube/model.mu"
mv "../GameData/Squad/Parts/Command/probeCoreCube/model000.dds.bak" "../GameData/Squad/Parts/Command/probeCoreCube/model000.dds"
mv "../GameData/Squad/Parts/Command/probeCoreCube/model001.dds.bak" "../GameData/Squad/Parts/Command/probeCoreCube/model001.dds"
mv "../GameData/Squad/Parts/Command/probeCoreHex/model.mu.bak" "../GameData/Squad/Parts/Command/probeCoreHex/model.mu"
mv "../GameData/Squad/Parts/Command/probeCoreHex/ksp_m_hexProbe_diff.dds.bak" "../GameData/Squad/Parts/Command/probeCoreHex/ksp_m_hexProbe_diff.dds"
mv "../GameData/Squad/Parts/Command/probeCoreHex/ksp_m_hexProbe_normal.dds.bak" "../GameData/Squad/Parts/Command/probeCoreHex/ksp_m_hexProbe_normal.dds"
mv "../GameData/Squad/Parts/Command/probeStackSmall/model.mu.bak" "../GameData/Squad/Parts/Command/probeStackSmall/model.mu"
mv "../GameData/Squad/Parts/Command/probeStackSmall/model000.dds.bak" "../GameData/Squad/Parts/Command/probeStackSmall/model000.dds"
mv "../GameData/Squad/Parts/Command/probeStackSmall/model001.dds.bak" "../GameData/Squad/Parts/Command/probeStackSmall/model001.dds"
mv "../GameData/Squad/Parts/Command/probeStackLarge/model.mu.bak" "../GameData/Squad/Parts/Command/probeStackLarge/model.mu"
mv "../GameData/Squad/Parts/Command/probeStackLarge/model000.dds.bak" "../GameData/Squad/Parts/Command/probeStackLarge/model000.dds"
mv "../GameData/Squad/Parts/Command/probeStackLarge/model001.dds.bak" "../GameData/Squad/Parts/Command/probeStackLarge/model001.dds"
