@echo off
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\ladder.dds.bak" "ladder.dds"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch NRM.dds.bak" "mk 1-2 external shell Variant-Hatch NRM.dds"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch.dds.bak" "mk 1-2 external shell Variant-Hatch.dds"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\walls.dds.bak" "walls.dds"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\window.dds.bak" "window.dds"
ren "..\GameData\Squad\Parts\Command\mk1Cockpit\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\mk1Cockpit\mk1Cockpit.dds.bak" "mk1Cockpit.dds"
ren "..\GameData\Squad\Parts\Command\mk1pod\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\mk1pod\hatch.dds.bak" "hatch.dds"
ren "..\GameData\Squad\Parts\Command\mk1pod\ladderrung.dds.bak" "ladderrung.dds"
ren "..\GameData\Squad\Parts\Command\mk1pod\outer shell NRM.dds.bak" "outer shell NRM.dds"
ren "..\GameData\Squad\Parts\Command\mk1pod\outer shell.dds.bak" "outer shell.dds"
ren "..\GameData\Squad\Parts\Command\mk1pod\window.dds.bak" "window.dds"
ren "..\GameData\Squad\Parts\Command\cupola\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\cupola\ksp_l_cupola_diff.dds.bak" "ksp_l_cupola_diff.dds"
ren "..\GameData\Squad\Parts\Command\cupola\ksp_l_cupola_normal.dds.bak" "ksp_l_cupola_normal.dds"
ren "..\GameData\Squad\Parts\Command\cupola\window.dds.bak" "window.dds"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\ladder.dds.bak" "ladder.dds"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\outershell.dds.bak" "outershell.dds"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\outershell_n.dds.bak" "outershell_n.dds"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\window.dds.bak" "window.dds"
ren "..\GameData\Squad\Parts\Command\mk1LanderCan\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\mk1LanderCan\ksp_s_landerCan_diff.dds.bak" "ksp_s_landerCan_diff.dds"
ren "..\GameData\Squad\Parts\Command\mk1LanderCan\ksp_s_landerCan_normal.dds.bak" "ksp_s_landerCan_normal.dds"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin.dds.bak" "cabin.dds"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin_n.dds.bak" "cabin_n.dds"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\window.dds.bak" "window.dds"
ren "..\GameData\Squad\Parts\Command\probeStackSphere\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\probeStackSphere\model000.dds.bak" "model000.dds"
ren "..\GameData\Squad\Parts\Command\probeStackSphere\model001.dds.bak" "model001.dds"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto2\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto2\model000.dds.bak" "model000.dds"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto\model000.dds.bak" "model000.dds"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto\model001.dds.bak" "model001.dds"
ren "..\GameData\Squad\Parts\Command\probeCoreCube\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\probeCoreCube\model000.dds.bak" "model000.dds"
ren "..\GameData\Squad\Parts\Command\probeCoreCube\model001.dds.bak" "model001.dds"
ren "..\GameData\Squad\Parts\Command\probeCoreHex\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\probeCoreHex\ksp_m_hexProbe_diff.dds.bak" "ksp_m_hexProbe_diff.dds"
ren "..\GameData\Squad\Parts\Command\probeCoreHex\ksp_m_hexProbe_normal.dds.bak" "ksp_m_hexProbe_normal.dds"
ren "..\GameData\Squad\Parts\Command\probeStackSmall\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\probeStackSmall\model000.dds.bak" "model000.dds"
ren "..\GameData\Squad\Parts\Command\probeStackSmall\model001.dds.bak" "model001.dds"
ren "..\GameData\Squad\Parts\Command\probeStackLarge\model.mu.bak" "model.mu"
ren "..\GameData\Squad\Parts\Command\probeStackLarge\model000.dds.bak" "model000.dds"
ren "..\GameData\Squad\Parts\Command\probeStackLarge\model001.dds.bak" "model001.dds"
