@echo off
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\ladder.dds" "ladder.dds.bak"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch NRM.dds" "mk 1-2 external shell Variant-Hatch NRM.dds.bak"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\mk 1-2 external shell Variant-Hatch.dds" "mk 1-2 external shell Variant-Hatch.dds.bak"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\walls.dds" "walls.dds.bak"
ren "..\GameData\Squad\Parts\Command\Mk1-2Pod\window.dds" "window.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1Cockpit\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\mk1Cockpit\mk1Cockpit.dds" "mk1Cockpit.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1pod\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\mk1pod\hatch.dds" "hatch.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1pod\ladderrung.dds" "ladderrung.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1pod\outer shell NRM.dds" "outer shell NRM.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1pod\outer shell.dds" "outer shell.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1pod\window.dds" "window.dds.bak"
ren "..\GameData\Squad\Parts\Command\cupola\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\cupola\ksp_l_cupola_diff.dds" "ksp_l_cupola_diff.dds.bak"
ren "..\GameData\Squad\Parts\Command\cupola\ksp_l_cupola_normal.dds" "ksp_l_cupola_normal.dds.bak"
ren "..\GameData\Squad\Parts\Command\cupola\window.dds" "window.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\ladder.dds" "ladder.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\outershell.dds" "outershell.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\outershell_n.dds" "outershell_n.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk2LanderCan\window.dds" "window.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1LanderCan\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\mk1LanderCan\ksp_s_landerCan_diff.dds" "ksp_s_landerCan_diff.dds.bak"
ren "..\GameData\Squad\Parts\Command\mk1LanderCan\ksp_s_landerCan_normal.dds" "ksp_s_landerCan_normal.dds.bak"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin.dds" "cabin.dds.bak"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\cabin_n.dds" "cabin_n.dds.bak"
ren "..\GameData\Squad\Parts\Command\hitchhikerStorageContainer\window.dds" "window.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeStackSphere\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\probeStackSphere\model000.dds" "model000.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeStackSphere\model001.dds" "model001.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto2\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto2\model000.dds" "model000.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto\model000.dds" "model000.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreOcto\model001.dds" "model001.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreCube\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreCube\model000.dds" "model000.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreCube\model001.dds" "model001.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreHex\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreHex\ksp_m_hexProbe_diff.dds" "ksp_m_hexProbe_diff.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeCoreHex\ksp_m_hexProbe_normal.dds" "ksp_m_hexProbe_normal.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeStackSmall\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\probeStackSmall\model000.dds" "model000.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeStackSmall\model001.dds" "model001.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeStackLarge\model.mu" "model.mu.bak"
ren "..\GameData\Squad\Parts\Command\probeStackLarge\model000.dds" "model000.dds.bak"
ren "..\GameData\Squad\Parts\Command\probeStackLarge\model001.dds" "model001.dds.bak"
